---
name: "get_config"
runner_type: "python-script"
description: "Get configuration from the device using NAPALM."
enabled: true
entry_point: "get_config.py"
parameters:
    hostname:
        type: "string"
        description: "The hostname of the device to connect to. Driver must be specified if hostname is not in configuration. Hostname without FQDN can be given if device is in configuration."
        required: true
        position: 0
    driver:
        type: "string"
        description: "Device driver name for connecting to device, see https://napalm.readthedocs.io/en/latest/support/index.html for list."
        required: false
        position: 1
    port:
        type: "string"
        description: "port for accessing device"
        required: false
        position: 2
    credentials:
        type: "string"
        description: "The credentials group which contains the username and password to log in"
        required: false
        position: 3
    retrieve:
        type: "string"
        description: "Configuration section to be retrieved"
        required: false
        position: 4
