---
name: "get_bgp_config"
runner_type: "python-script"
description: "Get BGP configuration from a device using NAPALM."
enabled: true
entry_point: "get_bgp_config.py"
parameters:
    driver:
        type: "string"
        description: "device type"
        required: true
        position: 0
    hostname:
        type: "string"
        description: "The hostname of the device to which you wish to post a configuration"
        required: true
        position: 1
    port:
        type: "string"
        description: "port for accessing device"
        required: false
        position: 2
    credentials:
        type: "string"
        description: "The credentials group which contains the username and password to log in"
        required: true
        position: 3
    group:
        type: "string"
        description: "Restrict configuration to this BGP Neighbour/Peer group"
        required: false
        position: 4
    neighbour:
        type: "string"
        description: "Restrict configuration to this BGP Neighbour"
        required: false
        position: 5
