---
name: "loadconfig"
runner_type: "python-script"
description: "Loads (merge) a configuration to a network device using NAPALM."
enabled: true
entry_point: "loadconfig.py"
parameters:
    hostname:
        type: "string"
        description: "The hostname of the device to connect to. Driver must be specified if hostname is not in configuration. Hostname without FQDN can be given if device is in configuration."
        required: true
        position: 0
    driver:
        type: "string"
        description: "Device driver name for connecting to device, see https://napalm.readthedocs.io/en/latest/support/index.html for list."
        required: false
        position: 1
    port:
        type: "string"
        description: "port for accessing device"
        required: true
        position: 2
    credentials:
        type: "string"
        description: "The credentials group which contains the username and password to log in"
        required: false
        position: 3
    config_file:
        type: "string"
        description: "configuration to load to device"
        required: true
        position: 4
    method:
        type: "string"
        description: "Method to load the config (either 'merge' or 'replace', default is 'merge')"
        required: false
        position: 5
