---
name: "loadconfig"
runner_type: "python-script"
description: "Loads (merge) a configuration to a network device using NAPALM."
enabled: true
entry_point: "loadconfig.py"
parameters:
    hostname:
        type: "string"
        description: "The hostname of the device to connect to. Driver must be specified if hostname is not in configuration. Hostname without FQDN can be given if device is in configuration."
        required: true
        position: 0
    driver:
        type: "string"
        description: "Device driver name for connecting to device, see https://napalm.readthedocs.io/en/latest/support/index.html for list."
        required: false
        position: 1
    port:
        type: "string"
        description: "port for accessing device"
        required: false
        position: 2
    credentials:
        type: "string"
        description: "The credentials group which contains the username and password to log in"
        required: false
        position: 3
    config_file:
        type: "string"
        description: "Absolute path to configuration file on local system that will be sent to the device. Need to specify either config_file or config_text. If both given, config_file takes precedence."
        required: false
        position: 4
    config_text:
        type: "string"
        description: "A command that will be sent to the device. Need to specify either config_file or config_text. If both given, config_file takes precedence."
        required: false
        position: 5
    method:
        type: "string"
        description: "Method to load the config (either 'merge' or 'replace', default is 'merge')"
        required: false
        position: 6
        enum:
            - merge
            - replace
        default: merge
    inline_transfer:
        type: "boolean"
        default: False
        description: "If selected, the ios driver will use SSH and not SCP to transfer config" 
        required: false
        position: 7
